package com.lupolov.telegram.bot;

public enum BotState {
    TRAINS_SEARCH,
    TRAINS_SEARCH_STARTED,
    TRAINS_SEARCH_FINISH,
    ASK_STATION_DEPART,
    ASK_STATION_ARRIVAL,
    SHOW_MAIN_MENU,
    SHOW_ABOUT_BOT,
    STATIONS_SEARCH,
    ASK_STATIONS_NAMEPART_DEPART,
    ASK_STATIONS_NAMEPART_ARRIVAL,
    STATIONS_SEARCH_DEPART_RECEIVED,
    STATIONS_SEARCH_ARRIVAL_RECEIVED,
    ASK_STATION_NAMEPART,
    STATION_NAMEPART_RECEIVED,
}
