server.port: 8080
telegrambot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  webHookPath: 'https://suburban-train-timetable-bot.herokuapp.com/'
localeTag: uk-UA
logging:
  level:
    root: info
