server.port: 8080
telegrambot:
  username: 'ivanlia_bot'
  token: '780177221:AAETBt4O9rnwr4k4LMqMN2ERcbdVXxULzEE'
  webHookPath: 'https://suburban-train-timetable-bot.herokuapp.com/'
localeTag: uk-UA
logging:
  level:
    root: info